//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 1/23/18.
//  Copyright (c) 2018 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var greyishBrown: UIColor { 
		return UIColor(white: 85.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var brownGrey: UIColor { 
		return UIColor(red: 125.0 / 255.0, green: 121.0 / 255.0, blue: 114.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var pinkishGrey: UIColor { 
		return UIColor(white: 203.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var black: UIColor { 
		return UIColor(white: 51.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var lightNavy: UIColor { 
		return UIColor(red: 20.0 / 255.0, green: 46.0 / 255.0, blue: 122.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var beige: UIColor { 
		return UIColor(red: 247.0 / 255.0, green: 243.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var lightGrey: UIColor { 
		return UIColor(red: 228.0 / 255.0, green: 222.0 / 255.0, blue: 211.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var greyish29: UIColor { 
		return UIColor(red: 167.0 / 255.0, green: 162.0 / 255.0, blue: 155.0 / 255.0, alpha: 0.29)
	}

	@nonobjc class var white: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

    @nonobjc class var whiteTwo: UIColor {
        return UIColor(white: 244.0 / 255.0, alpha: 1.0)
    }

    @nonobjc class var greyish: UIColor {
        return UIColor(white: 176.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var softBlue: UIColor {
        return UIColor(red: 93 / 255.0, green: 129 / 255.0, blue: 233 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var deepOrange: UIColor {
        return UIColor(red: 234 / 255.0, green: 92 / 255.0, blue: 6 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var warmGrey: UIColor {
        return UIColor(red: 140 / 255.0, green: 140 / 255.0, blue: 140 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var whiteThree: UIColor {
        return UIColor(red: 232 / 255.0, green: 232 / 255.0, blue: 232 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var pinkishGreyTwo: UIColor {
        return UIColor(red: 204 / 255.0, green: 204 / 255.0, blue: 204 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var greyishTwo: UIColor {
        return UIColor(red: 175 / 255.0, green: 175 / 255.0, blue: 175 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var greyishBrownTwo: UIColor {
        return UIColor(red: 85 / 255.0, green: 85 / 255.0, blue: 85 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var niceBlue: UIColor {
        return UIColor(red: 9 / 255.0, green: 105 / 255.0, blue: 186 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var warmGreyThree: UIColor {
        return UIColor(red: 134 / 255.0, green: 134 / 255.0, blue: 134 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var warmGreyFour: UIColor {
        return UIColor(red: 123 / 255.0, green: 123 / 255.0, blue: 123 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var warmGreyFive: UIColor {
        return UIColor(red: 125 / 255.0, green: 125 / 255.0, blue: 125 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var ultramarineBlue: UIColor {
        return UIColor(red: 17 / 255.0, green: 34 / 255.0, blue: 204 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var greyishThree: UIColor {
        return UIColor(red: 170 / 255.0, green: 170 / 255.0, blue: 170 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var whiteFour: UIColor {
        return UIColor(red: 240 / 255.0, green: 240 / 255.0, blue: 240 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var greyishFour: UIColor {
        return UIColor(red: 169 / 255.0, green: 169 / 255.0, blue: 169 / 255.0, alpha: 1.0)
    }
    
}

extension UIColor {
    static var globalTint: UIColor {
        return UIColor(hex: 0x183175)
    }
    
    static var loginButtonBackground: UIColor {
        return UIColor(hex: 0x102151)
    }
    
    static var buttonBackground: UIColor {
        return UIColor.globalTint
    }
    
    static var buttonShadow: UIColor {
        return UIColor(hex: 0x1F3679)
    }
    
    static var lightButtonBackground: UIColor {
        return UIColor.white
    }
    
    static var lightButtonShadow: UIColor {
        return UIColor(hex: 0xCBCBCB)
    }
}
